const MOCK_JOBS = [
  {
    title_ku: 'گەشەپێدەری ئەپی مۆبایل (React Native)',
    title_en: 'Mobile App Developer (React Native)',
    company: 'Kurd24 Tech Solutions',
    industry: 'tech',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    city_ku: 'erbil',
    city_en: 'erbil',
    category: 'software',
    type: 'fullTime',
    experience_level: 'mid',
    salary: '$1,500 - $2,200',
    description_ku: 'ئێمە بەدوای گەشەپێدەرێکی لێهاتووی React Native دەگەڕێین بۆ دروستکردن و باشترکردنی ئەپی مۆبایلی هاوچەرخ. کارەکە لە نوسینگەی هەولێر دەبێت لەگەڵ تیمێکی فرەچەشن.',
    description_en: 'We are looking for a skilled React Native developer to design and build next-generation mobile applications. You will join our high-performing tech team based in Erbil.',
    requirements_ku: 'ئەزموونی بەکارهێنانی React Native بۆ ٢ ساڵ یان زیاتر\nتێگەیشتن لە کارکردنی Redux یان App Context\nشارەزایی لە خزمەتگوزارییەکانی REST API و Supabase\nتوانای قسەکردن بە زمانی کوردی و ئینگلیزی',
    requirements_en: '2+ years of professional React Native development experience\nSolid understanding of state management (Redux, Context API)\nExperience integrating REST APIs, Supabase, or Firebase\nStrong communication skills in Kurdish and English',
    whatsapp: '9647501234567',
    email: 'hr@kurd24.job',
    status: 'published',
    views: 245,
    clicks: 43,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'دیزاینەری باڵای UI/UX',
    title_en: 'Senior UI/UX Designer',
    company: 'Hewlêr Media Group',
    industry: 'design',
    logo_url: 'https://images.unsplash.com/photo-1618005198143-e5283b519a7f?w=150&auto=format&fit=crop&q=80',
    city_ku: 'erbil',
    city_en: 'erbil',
    category: 'design',
    type: 'fullTime',
    experience_level: 'senior',
    salary: '$1,800 - $2,500',
    description_ku: 'دیزاینەرێکی باڵامان دەوێت بۆ دروستکردنی کارلێک و ڕووکاری کاربەرهێنەری ناوازە بۆ وێبسایت و ئەپەکانمان. پێویستە خاوەن پرۆفایلی بەهێز بێت لە Figma.',
    description_en: 'We are seeking a senior UI/UX designer to create stunning user interfaces and experiences for our media portals. Figma proficiency and a strong portfolio are required.',
    requirements_ku: '٤ ساڵ کارکردنی ڕاستەقینە لە دیزاینی دیجیتاڵیدا\nتوانای نوێکردنەوە و پێشخستنی شێوازی دیزاینی گلاسی و نیۆن\nشارەزایی تەواو لە Figma و Adobe Suite\nئامادەکردنی پرۆتۆتایپی پێشکەوتوو',
    requirements_en: '4+ years of professional digital design experience\nExperience designing modern, glassmorphic, and minimalist interfaces\nMastery of Figma, design systems, and prototyping tools\nAbility to present user flows and conduct usability testing',
    whatsapp: '9647507654321',
    email: 'careers@hewlermedia.net',
    status: 'published',
    views: 189,
    clicks: 29,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'بەڕێوەبەری مارکێتینگ و سۆشیاڵ میدیا',
    title_en: 'Social Media Marketing Manager',
    company: 'Silêmanî Trading Co.',
    industry: 'retail',
    logo_url: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?w=150&auto=format&fit=crop&q=80',
    city_ku: 'sulaymaniyah',
    city_en: 'sulaymaniyah',
    category: 'marketing',
    type: 'fullTime',
    experience_level: 'mid',
    salary: 'IQD 1,500,000',
    description_ku: 'ئەرکی تۆ داڕشتنی پلانی مارکێتینگ دەبێت لە سۆشیاڵ میدیادا بۆ بەرزکردنەوەی فرۆش و ناساندنی زیاتری کاڵاکانمان لە پارێزگای سلێمانی و دەوروبەری.',
    description_en: 'You will manage social media advertising campaigns, content creation, and brand engagement to drive sales and awareness across Sulaymaniyah.',
    requirements_ku: 'ئەزموونی ٢ ساڵ لە مارکێتینگی سۆشیاڵ میدیا\nتوانای نووسینی ناوەڕۆکی سەرنجڕاکێش بە کوردی و عەرەبی\nشارەزایی لە بەڕێوەبردنی کامپەینی سپۆنسەر (Facebook/Instagram Ads)\nئاشنایی بە ئامرازەکانی شیکاری سۆشیاڵ میدیا',
    requirements_en: '2+ years of social media marketing experience\nAbility to write engaging copy in Kurdish and Arabic\nExperience running paid Meta campaigns (FB/IG Ads Manager)\nFamiliarity with marketing analytics and scheduling tools',
    whatsapp: '9647701122334',
    email: 'info@silemanitrading.com',
    status: 'published',
    views: 110,
    clicks: 18,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'وەرگێڕی یاسایی (کوردی - ئینگلیزی)',
    title_en: 'Legal Translator (Kurdish - English)',
    company: 'Kurdish Localization Hub',
    industry: 'education',
    logo_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=150&auto=format&fit=crop&q=80',
    city_ku: 'remote',
    city_en: 'remote',
    category: 'translation',
    type: 'remote',
    experience_level: 'lead',
    salary: '$800 - $1,200',
    description_ku: 'وەرگێڕانی بەڵگەنامە فەرمییەکان و گرێبەستەکان لە زمانی ئینگلیزییەوە بۆ کوردی (سۆرانی و بادینی) بە شێوازێکی زانستی و یاسایی دروست.',
    description_en: 'Translate official documentation, contracts, and policies from English to Central Kurdish (Sorani) and Northern Kurdish (Badini) with legal accuracy.',
    requirements_ku: 'بڕوانامەی بەکالۆریۆس لە زمان یان وەرگێڕاندا\nئەزموونی کارکردن وەک وەرگێڕی فەرمی لانی کەم ٣ ساڵ\nدیسپلینی بەرز بۆ کارکردنی دوور و پابەندبوون بە کاتی دیاریکراو',
    requirements_en: 'Bachelor’s degree in English, Translation, or related field\n3+ years of professional translation experience, legal background preferred\nStrong self-discipline for remote work and meeting deadlines',
    whatsapp: '9647509998877',
    email: 'apply@kurdlocalization.org',
    status: 'published',
    views: 94,
    clicks: 22,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'ئەندازیاری شارستانی (پڕۆژەی نیشتەجێبوون)',
    title_en: 'Civil Engineer (Residential Project)',
    company: 'Duhok Build Ltd',
    industry: 'engineering',
    logo_url: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=150&auto=format&fit=crop&q=80',
    city_ku: 'duhok',
    city_en: 'duhok',
    category: 'engineering',
    type: 'contract',
    experience_level: 'mid',
    salary: '$1,200',
    description_ku: 'پێویستمان بە ئەندازیارێکی شارستانی هەیە بۆ چاودێریکردن و سەرپەرشتیکردنی پڕۆژەیەکی نوێی نیشتەجێبوون لە دهۆک.',
    description_en: 'We need a civil engineer to oversee a new residential construction project in Duhok.',
    requirements_ku: 'بڕوانامەی ئەندازیاری شارستانی\nشارەزایی لە AutoCAD و بەرنامەکانی چاودێری پڕۆژە\nکارکردن لە دهۆک',
    requirements_en: 'Degree in Civil Engineering\nProficiency in AutoCAD and structural analysis software\nBased in or willing to relocate to Duhok',
    whatsapp: '9647502223344',
    email: 'jobs@duhokbuild.com',
    status: 'published',
    views: 45,
    clicks: 2,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'مامۆستای زمانی ئینگلیزی',
    title_en: 'English Language Teacher',
    company: 'Duhok International Academy',
    industry: 'education',
    logo_url: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=150&auto=format&fit=crop&q=80',
    city_ku: 'duhok',
    city_en: 'duhok',
    category: 'education',
    type: 'fullTime',
    experience_level: 'mid',
    salary: '$1,000 - $1,300',
    description_ku: 'قوتابخانەکەمان لە دهۆک بەدوای مامۆستایەکی لێهاتوو دەگەڕێت بۆ وتنەوەی وانەی ئینگلیزی بە پۆلەکانی ناوەندی و ئامادەیی.',
    description_en: 'Our academy in Duhok is hiring a qualified English teacher for middle and high school students.',
    requirements_ku: 'بڕوانامەی بەکالۆریۆس لە زمانی ئینگلیزی\nلانی کەم ٢ ساڵ ئەزموونی وانەوتنەوە\nخاوەن کەسایەتی گونجاو و مامەڵەی باش لەگەڵ قوتابیان',
    requirements_en: 'Bachelor\'s degree in English Literature or Education\n2+ years of classroom teaching experience\nStrong interpersonal and classroom management skills',
    whatsapp: '9647501112223',
    email: 'hr@duhokacademy.edu.krd',
    status: 'published',
    views: 78,
    clicks: 12,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'دیزاینەری گرافیک (کاروباری ڕیکلام)',
    title_en: 'Graphic Designer (Advertising)',
    company: 'Slemani Creative Studio',
    industry: 'design',
    logo_url: 'https://images.unsplash.com/photo-1561070791-26c113006238?w=150&auto=format&fit=crop&q=80',
    city_ku: 'sulaymaniyah',
    city_en: 'sulaymaniyah',
    category: 'design',
    type: 'partTime',
    experience_level: 'junior',
    salary: 'IQD 800,000',
    description_ku: 'دیزاینەرێکی گرافیکمان دەوێت بۆ دروستکردنی دیزاینی سۆشیاڵ میدیا و لۆگۆ بە شێوەی نیوەکات لە ستۆدیۆکەمان لە سلێمانی.',
    description_en: 'We are seeking a part-time graphic designer to create social media posts and branding visual assets at our studio in Sulaymaniyah.',
    requirements_ku: 'شارەزایی لە Adobe Photoshop و Illustrator\nپێشکەشکردنی نموونەی دیزاینەکانی پێشوو (Portfolio)\nئامادەبوون بۆ کارکردنی تیم و هاوبەش',
    requirements_en: 'Proficiency in Adobe Photoshop, Illustrator, or Canva\nPortfolio showcasing branding/social media work\nHigh creativity and ability to work in a collaborative environment',
    whatsapp: '9647704445566',
    email: 'design@slemanistudio.com',
    status: 'published',
    views: 132,
    clicks: 34,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'پسپۆڕی مارکێتینگی دیجیتاڵی',
    title_en: 'Digital Marketing Specialist',
    company: 'Hewlêr Agency',
    industry: 'retail',
    logo_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&auto=format&fit=crop&q=80',
    city_ku: 'erbil',
    city_en: 'erbil',
    category: 'marketing',
    type: 'remote',
    experience_level: 'mid',
    salary: '$1,200',
    description_ku: 'داڕشتن و بەڕێوەبردنی کامپەینەکانی ڕیکلام لەسەر گووگڵ و تۆڕە کۆمەڵایەتییەکان بە شێوازی دوورەکار (Remote).',
    description_en: 'Manage paid advertisement search/social campaigns (Google Ads, Meta Ads) remotely for our Erbil office clients.',
    requirements_ku: 'بڕوانامەی فەرمی لە Google Ads یان Meta Blueprint\nئەزموونی بەڕێوەبردنی بودجەی ڕیکلام\nتوانای شیکارکردنی ئەنجامەکان و پێشکەشکردنی ڕاپۆرت',
    requirements_en: 'Certification in Google Ads or Meta Ads\nProven track record managing paid advertising budgets\nAbility to analyze campaign performance and generate reports',
    whatsapp: '9647508889900',
    email: 'info@hewleragency.com',
    status: 'published',
    views: 89,
    clicks: 19,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'نووسەری ناوەڕۆک (کوردی و عەرەبی)',
    title_en: 'Content Writer (Kurdish & Arabic)',
    company: 'Hewlêr Press Group',
    industry: 'media',
    logo_url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=150&auto=format&fit=crop&q=80',
    city_ku: 'remote',
    city_en: 'remote',
    category: 'translation',
    type: 'remote',
    experience_level: 'mid',
    salary: '$900',
    description_ku: 'ئێمە بەدوای نووسەرێکی ناوەڕۆکی بەهرەمەند دەگەڕێین بۆ نووسینی وتار، ڕاپۆرت و بڵاوکراوەی سۆشیاڵ میدیا بە هەردوو زمانی کوردی و عەرەبی بە شێوەی دوورەکار (Remote).',
    description_en: 'We are looking for a talented content writer to create articles, reports, and social media updates in both Kurdish and Arabic remotely.',
    requirements_ku: 'شارەزایی تەواو لە نووسینی کوردی و عەرەبی بە شێوەیەکی زمانەوانی دروست\nئەزموونی نووسینی پێشوو لانی کەم ٢ ساڵ\nتوانای پابەندبوون بە کاتی پێشکەشکردنی بابەتەکان',
    requirements_en: 'Excellent writing skills in both Kurdish and Arabic\n2+ years of professional writing or blogging experience\nAbility to work independently and meet tight deadlines',
    whatsapp: '9647503334455',
    email: 'editor@hewlerpress.net',
    status: 'published',
    views: 65,
    clicks: 8,
    created_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    title_ku: 'پسپۆڕی پشتیوانی IT',
    title_en: 'IT Support Specialist',
    company: 'Kirkuk Oil Services Co.',
    industry: 'tech',
    logo_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=150&auto=format&fit=crop&q=80',
    city_ku: 'kirkuk',
    city_en: 'kirkuk',
    category: 'software',
    type: 'fullTime',
    experience_level: 'junior',
    salary: 'IQD 1,200,000',
    description_ku: 'پێویستمان بە کارمەندێکی لێهاتووە بۆ چاودێریکردن و پێشکەشکردنی پشتیوانی تەکنیکی بۆ سیستمەکان و تۆڕەکان لە نوسینگەی کەرکوک.',
    description_en: 'We are seeking an IT Support Specialist to maintain computers, servers, and networks, providing technical support at our Kirkuk office.',
    requirements_ku: 'بڕوانامەی بەکالۆریۆس لە زانستی کۆمپیوتەر یان تەکنەلۆژیای زانیاری\nشارەزایی لە کێشە چارەسەرکردنی ڕەقەکاڵا و نەرمەکاڵا\nئەزموونی ١ ساڵ لە پشتیوانی IT',
    requirements_en: 'Bachelor\'s degree in Computer Science, IT, or related field\nGood troubleshooting skills in hardware, software, and networks\n1+ years of IT support experience',
    whatsapp: '9647708887766',
    email: 'support@kirkukoilsol.com',
    status: 'published',
    views: 120,
    clicks: 14,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

const supabaseUrl = 'https://ojhminrrkkxwyybpgvrs.supabase.co';
const supabaseKey = 'sb_publishable_c0y0Fx3rb1O1kIXGTgcskg_SZeezhmX';

async function seed() {
  console.log('Sending mock jobs to Supabase REST endpoint...');
  try {
    // 1. Delete all current jobs
    console.log('Deleting existing jobs on Supabase...');
    const delRes = await fetch(`${supabaseUrl}/rest/v1/jobs?id=not.is.null`, {
      method: 'DELETE',
      headers: {
        'apikey': supabaseKey,
        'Authorization': `Bearer ${supabaseKey}`,
      }
    });

    console.log('Delete response status:', delRes.status);
    
    // 2. Insert mock jobs
    console.log('Inserting 10 mock jobs...');
    const insRes = await fetch(`${supabaseUrl}/rest/v1/jobs`, {
      method: 'POST',
      headers: {
        'apikey': supabaseKey,
        'Authorization': `Bearer ${supabaseKey}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=representation'
      },
      body: JSON.stringify(MOCK_JOBS)
    });

    console.log('Insert response status:', insRes.status);
    const data = await insRes.json();
    if (insRes.status >= 200 && insRes.status < 300) {
      console.log('SUCCESS! Seeded 10 jobs to Supabase.');
      console.log('Inserted count:', data.length);
    } else {
      console.error('FAILED to seed. Error response:', data);
    }
  } catch (error) {
    console.error('Fetch error:', error);
  }
}

seed();
